### Register User API
POST http://localhost:8000/api/users/
Content-Type: application/json
Accept: application/json
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36

{
    "username": "hanchanp2",
    "password": "rahasia1232",
    "name": "HandikaCP2"
}


### Login User API
POST localhost:8000/api/users/login
Accept: application/json
Content-Type: application/json
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36

{
    "username": "hanchanp2",
    "password": "rahasia1232"
}

### Get Current User API
GET localhost:8000/api/users/current
Accept: application/json
Authorization: Bearer 4|oFeqQX4kKa44NnvgWSOYygn9NfydCnTwsJGUoztx636e30b4

### Update User API
PATCH localhost:8000/api/users/current
Content-Type: application/json
Accept: application/json
Authorization: 317d6d4c-734d-4263-9e00-420f93d4705c

{
    "name": "Handika C P"
}


### Logout User API
DELETE localhost:8000/api/users/logout
Authorization: Bearer 27|ZrPHA8fQC1do7t5NNKoU5HrxJ7mSpor966NvloXG80eac5f7
Accept: application/json

### Create Contact API
POST http://localhost:8000/api/contacts
Content-Type: application/json
Accept: application/json
Authorization: 6c97d859-dee2-4600-b79f-72bb1301fcc1

{
    "first_name": "Dika",
    "last_name": "dika",
    "email": "handika@gmail.com",
    "phone": "+62 812 3456 7890"
}

### Get Contact API 586
GET http://localhost:8000/api/contacts/1738
Accept: application/json
Authorization: 6c97d859-dee2-4600-b79f-72bb1301fcc1

### Update Contact API 586
PUT http://localhost:8000/api/contacts/586
Content-Type: application/json
Accept: application/json
Authorization: 317d6d4c-734d-4263-9e00-420f93d4705c

{
    "first_name": "new hanchan",
    "last_name": "new dika",
    "email": "new@gmail.com",
    "phone": "+62 812 3456 7890"
}

### Delete Contact API 585
DELETE http://localhost:8000/api/contacts/585
Accept: application/json
Authorization: 317d6d4c-734d-4263-9e00-420f93d4705c

### Search Contact API
#GET http://localhost:8000/api/contacts?size=2&page=1&name=han
GET http://localhost:8000/api/contacts
Accept: application/json
Authorization: 317d6d4c-734d-4263-9e00-420f93d4705c


### Create Address API
POST http://localhost:8000/api/contacts/1738/addresses
Content-Type: application/json
Accept: application/json
Authorization: 6c97d859-dee2-4600-b79f-72bb1301fcc1

{
    "street": "pwk 4",
    "city": "pwk",
    "province": "jabar",
    "country": "indo",
    "postal_code": "123123"
}

### Get Address API 43
GET http://localhost:8000/api/contacts/1738/addresses/316
Accept: application/json
Authorization: 6c97d859-dee2-4600-b79f-72bb1301fcc1

### Update Address API 43
PUT http://localhost:8000/api/contacts/586/addresses/43
Content-Type: application/json
Accept: application/json
Authorization: 317d6d4c-734d-4263-9e00-420f93d4705c

{
    "street": "bdg",
    "city": "bdg",
    "province": "jabar",
    "country": "indo",
    "postal_code": "123123"
}


### Delete Address API 43
DELETE http://localhost:8000/api/contacts/586/addresses/40
Accept: application/json
Authorization: 317d6d4c-734d-4263-9e00-420f93d4705c

### List Address API
GET http://localhost:8000/api/contacts/1739/addresses
Accept: application/json
Authorization: 6c97d859-dee2-4600-b79f-72bb1301fcc1

