<?php

namespace Tests\Feature;

use App\Models\User;
use App\Services\UserService;
use Database\Seeders\UserSeeder;
use Laravel\Sanctum\Sanctum;
use Tests\TestCase;

class UserTest extends TestCase
{

    public UserService $userService;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->userService = $this->app->make(UserService::class);
    }
    public function testRegisterSuccess()
    {
        $this->post('/api/users', [
            'username' => 'hanchan',
            'password' => 'rahasia',
            'name' => 'Handika'
        ])
            ->assertStatus(201)
            ->assertJson([
                'data' => [
                    'username' => 'hanchan',
                    'name' => 'Handika'
                ]
            ]);
    }

    public function testRegisterFailed()
    {
        $this->post('/api/users', [
            'username' => '',
            'password' => '',
            'name' => ''
        ])
            ->assertStatus(400)
            ->assertJson([
                'errors' => [
                    'username' => [
                        'The username field is required.'
                    ],
                    'password' => [
                        'The password field is required.'
                    ],
                    'name' => [
                        'The name field is required.'
                    ]
                ]
            ]);
    }

    public function testRegisterUsernameAlreadyTaken()
    {
        $this->testRegisterSuccess();

        $this->post('/api/users', [
            'username' => 'hanchan',
            'password' => 'rahasia',
            'name' => 'handika'
        ])
            ->assertStatus(400)
            ->assertJson([
                'errors' => [
                    'username' => [
                        'Username is already taken'
                    ]
                ]
            ]);
    }

    public function testLoginSuccess()
    {
        $this->seed(UserSeeder::class);

        $response = $this->postJson('/api/users/login', [
            'username' => 'dummy',
            'password' => 'dummy',
        ]);

        $response->assertStatus(200)
            ->assertJsonStructure([
                'access_token',
                'token_type',
                'data' => [
                    'username',
                    'name'
                ]
            ]);

        $this->assertDatabaseHas('users', [
            'username' => 'dummy'
        ]);

        $this->assertDatabaseCount('personal_access_tokens', 1);
        $user = User::query()->where('username', "=", 'dummy')->first();
        $this->userService->logout($user, $response['access_token']);
        $freshUser = $user->fresh();
        self::assertCount(0, $freshUser->tokens);
    }


    public function testLoginFailed()
    {
        $this->seed(UserSeeder::class);

        $this->post('/api/users/login', [
            'username' => 'test',
            'password' => 'dummy',
        ])->assertStatus(404)
            ->assertJson([
                "errors" => [
                    'message' => [
                        'username and password combination is incorrect'
                    ]
                ]
            ]);
    }



    public function testGetSuccess()
    {
        $this->seed(UserSeeder::class);

        $user = User::where('username', 'dummy')->first();
        Sanctum::actingAs($user);

        $this->getJson('/api/users/current')
            ->assertStatus(200)
            ->assertJson([
                'data' => [
                    'username' => 'dummy',
                    'name' => 'dummy'
                ]
            ]);


        // atau klo mau full flow
        $response = $this->postJson('/api/users/login', [
            'username' => 'dummy',
            'password' => 'dummy',
        ]);

        $token = $response->json('access_token');

        $this->withHeaders([
            'Authorization' => 'Bearer ' . $token,
        ])->getJson('/api/users/current')
            ->assertStatus(200);

        $user = User::query()->where('username', "=", 'dummy')->first();
        $this->userService->logout($user, $response['access_token']);
        $freshUser = $user->fresh();
        self::assertCount(0, $freshUser->tokens);

    }


    public function testGetUnauthorized()
    {
        $this->seed(UserSeeder::class);
        $this->get('/api/users/current')
            ->assertStatus(401)
            ->assertJson([
                'errors' => [
                    'message' => [
                        'Unauthenticated'
                    ]
                ]
            ]);
    }

    public function testGetInvalidToken()
    {
        $this->seed(UserSeeder::class);

        $this->get('/api/users/current', [
            'Accept' => 'application/json',
            'Authorization' => 'salah'
        ])
            ->assertStatus(401)
            ->assertJson([
                'errors' => [
                    'message' => [
                        'Unauthenticated'
                    ]
                ]
            ]);
    }

    public function testUpdateNameSuccess()
    {
        $this->seed(UserSeeder::class);
        $oldUser = User::query()->where('username', 'dummy')->first();

        $user = User::query()->where('username', 'dummy')->first();
        Sanctum::actingAs($user);

        $this->patchJson('/api/users/current', [
            'name' => 'baru'
        ])
            ->assertStatus(200)
            ->assertJson([
                'data' => [
                    'username' => 'dummy',
                    'name' => 'baru'
                ]
            ]);

        $newUser = User::query()->where('username', 'dummy')->first();
        self::assertNotEquals($oldUser->name, $newUser->name);
    }

    public function testUpdatePasswordSuccess()
    {
        $this->seed(UserSeeder::class);
        $oldUser = User::query()->where('username', 'dummy')->first();

        $user = User::query()->where('username', 'dummy')->first();
        Sanctum::actingAs($user);

        $this->patchJson('/api/users/current', [
            'password' => 'baru'
        ])
            ->assertStatus(200)
            ->assertJson([
                'data' => [
                    'username' => 'dummy',
                    'name' => 'dummy'
                ]
            ]);

        $newUser = User::query()->where('username', 'dummy')->first();
        self::assertNotEquals($oldUser->password, $newUser->password);
    }

    public function testUpdateFailed()
    {
        $this->seed(UserSeeder::class);

        $user = User::query()->where('username', 'dummy')->first();
        Sanctum::actingAs($user);

        $this->patchJson('/api/users/current', [
            'name' => 'barubarubarubarubarubarubarubarubarubarubarubarubarubarubarubarubarubarubarubarubarubarubarubarubarubarubarubarubarubarubarubarubarubarubarubarubarubaru',
            'password' => 'barubarubarubarubarubarubarubarubarubarubarubarubarubarubarubarubarubarubarubarubarubarubarubarubarubarubarubarubarubarubarubarubarubarubarubarubarubaru'
        ])
            ->assertStatus(400)
            ->assertJson([
                'errors' => [
                    'name' => [
                        'The name field must not be greater than 100 characters.'
                    ],
                    'password' => [
                        'The password field must not be greater than 100 characters.'
                    ]
                ]
            ]);
    }

    public function testLogoutSuccess()
    {
        $this->seed(UserSeeder::class);

        $user = User::query()->where('username', 'dummy')->first();
        $response = $this->postJson('/api/users/login', [
            'username' => 'dummy',
            'password' => 'dummy',
        ]);
        $token = $response->json('access_token');


        $this->withHeaders([
            'Authorization' => 'Bearer ' . $token,
        ])->deleteJson('/api/users/logout')
            ->assertStatus(200)
            ->assertJson([
                "data" => true
            ]);

        $freshUser = $user->fresh();
        self::assertCount(0, $freshUser->tokens);
    }

    public function testLogoutFailed()
    {
        $this->seed(UserSeeder::class);

        $this->delete(uri: '/api/users/logout', headers: [
            'Authorization' => 'salah'
        ])
            ->assertStatus(401)
            ->assertJson([
                'errors' => [
                    'message' => [
                        'Unauthenticated'
                    ]
                ]
            ]);
    }


}


